### ISSUE TITLE
Pathway use case not working

### ISSUE THREAD

**Issue by mstreit** [Caleydo/pathfinder#137]
![image](https://cloud.githubusercontent.com/assets/4129755/20760754/21397e84-b721-11e6-9630-c043fb110950.png)

**Comment by cpartl** [comment]
Maybe the pathway database is down? @sgratzl can you check?

**Comment by mstreit** [comment]
Sam is on vacation until next week. @cpartl, do you also know how to check it?

**Comment by cpartl** [comment]
On my local installation, yes. But I never dealt with the deployed system.

**Comment by mstreit** [comment]
Is the pathway DB hosted on AWS or on the TUG server?

**Comment by cpartl** [comment]
AWS afaik.

**Comment by mstreit** [comment]
@sgratzl restarted the DB, which fixed the problem.
